# Generated by Django 5.0.4 on 2024-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='decryption_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
